- alicloud/common_columns.go
- alicloud/plugin.go
- alicloud/service.go
- alicloud/table_alicloud_ecs_disk.go
- alicloud/utils.go
> Add alicloud_ecs_disk table. Closes #3

- docs/index.md
> Service description link fix

- alicloud/table_alicloud_action_trail.go
<details>
```
```
</details>
<details>
```
```
</details>
> remove mns_topic_arn column from action_trail table . Closes #138

- alicloud/table_alicloud_ecs_instance.go
- docs/tables/alicloud_ecs_instance.md
<details>
```
```
</details>
<details>
```
```sql
select
instance_id,
name,
arn,
status,
instance_type,
os_name_en,
public_ip_address,
private_ip_address,
zone
from
alicloud_ecs_instance;
+------------------------+-------------------------+-------------------------------------------------------------------------+---------+---------------+------------------------------------+-------------------+--------------------+-------------+
| instance_id            | name                    | arn                                                                     | status  | instance_type | os_name_en                         | public_ip_address | private_ip_address | zone        | …
> Add column arn for the table alicloud_ecs_instance. Closes #142

- alicloud/table_alicloud_ecs_disk.go
- docs/tables/alicloud_ecs_disk.md
<details>
```
```
</details>
<details>
```
```sql
select
name,
disk_id,
arn,
size,
type,
billing_method,
zone,
region
from
alicloud_ecs_disk;
+------+------------------------+---------------------------------------------------------------------+------+--------+----------------+-------------+------------+
| name | disk_id                | arn                                                                 | size | type   | billing_method | zone        | region     |
+------+------------------------+---------------------------------------------------------------------+------+--------+----------------+-------------+------------+
|      | d-a2ddrvobltfdigk7aj1w | …
> Add column arn for the table alicloud_ecs_disk. Closes #143

- alicloud/table_alicloud_rds_instance.go
- docs/tables/alicloud_rds_instance.md
<details>
```
```
</details>
<details>
```
```sql
select
db_instance_id,
arn,
vpc_id,
creation_time,
engine
from
alicloud_rds_instance;
+----------------------+-----------------------------------------------------------------------+---------------------------+---------------------+------------+
| db_instance_id       | arn                                                                   | vpc_id                    | creation_time       | engine     |
+----------------------+-----------------------------------------------------------------------+---------------------------+---------------------+------------+
| pgm-6gj950v5gnc8bqar | arn:acs:rds:ap-south-1:5982111499156037:instance/pgm-6gj950v5gnc8bqar …
> Add column arn for the table alicloud_rds_instance. Closes #147

- alicloud/table_alicloud_rds_instance.go
<details>
```
```
</details>
<details>
```
> select db_instance_id,arn,sql_collector_retention,sql_collector_policy from alicloud_rds_instance
+----------------------+----------------------------------------------------------------------+-------------------------+-----------------------------------------------------------------------------------
| db_instance_id       | arn                                                                  | sql_collector_retention | sql_collector_policy                                                              
+----------------------+----------------------------------------------------------------------+-------------------------+------------------------------------ …
```
> Add column audit_status, audit_retention_duration for table alicloud_rds_instance. Closes #149, Closes #150, Closes #158

- alicloud/table_alicloud_ecs_image.go
- docs/tables/alicloud_ecs_image.md
<details>
```
```
</details>
<details>
```
```sql
select
name,
image_id,
arn,
size,
status,
usage
from
alicloud_ecs_image;
+---------------------------------------------------------------+---------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+------+-----------+----------+
| name                                                          | image_id                                                      | arn                                                                                                         | size | status    | usage    | …
> Add column arn for the table alicloud_ecs_image. Closes #144

- alicloud/table_alicloud_ecs_security_group.go
<details>
```
```
</details>
<details>
```
```sql
select
name,
security_group_id,
arn,
type,
inner_access_policy
from
alicloud_ecs_security_group;
+-------------------------+-------------------------+-------------------------------------------------------------------------------+--------+---------------------+
| name                    | security_group_id       | arn                                                                           | type   | inner_access_policy |
+-------------------------+-------------------------+-------------------------------------------------------------------------------+--------+---------------------+
| sg-a2dghywrhqb8q26bqdqf | sg-a2dghywrhqb8q26bqdqf | …
> Add column arn for the table alicloud_ecs_security_group. Closes #145

- alicloud/table_alicloud_oss_bucket.go
- docs/tables/alicloud_oss_bucket.md
<details>
```
```
</details>
<details>
```
select name,arn,creation_date,versioning from alicloud_oss_bucket
+-----------------+-------------------------------+---------------------+------------+
| name            | arn                           | creation_date       | versioning |
+-----------------+-------------------------------+---------------------+------------+
| test-ap-south-1 | arn:acs:oss:::test-ap-south-1 | 2021-02-24 09:49:39 | Enabled    |
| canonical-test  | arn:acs:oss:::canonical-test  | 2021-03-03 09:36:40 |            |
| kms-bucket      | arn:acs:oss:::kms-bucket      | 2021-02-25 00:02:56 | Enabled    |
| cis-test2       | arn:acs:oss:::cis-test2       | 2021-03-12 12:00:22 | …
```
> Add column arn for the table alicloud_oss_bucket. Closes #146

- alicloud/table_alicloud_ecs_autoscaling_group.go
- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
> select
name,
load_balancer_ids,
default_cooldown,
active_capacity,
desired_capacity,
min_size,
max_size
from
alicloud_ecs_autoscaling_group;
+---------+-------------------+------------------+-----------------+------------------+----------+----------+
| name    | load_balancer_ids | default_cooldown | active_capacity | desired_capacity | min_size | max_size |
+---------+-------------------+------------------+-----------------+------------------+----------+----------+
| js_as_1 | []                | 60               | <null>          | <null>           | <null>   | 4        |
+---------+-------------------+------------------+-----------------+---------------- …
```
> fix request parameter in alicloud_ecs_autoscaling_group table. Closes #171

- alicloud/table_alicloud_ecs_snapshot.go
- docs/tables/alicloud_ecs_snapshot.md
<details>
```
```
</details>
<details>
```
select
name,
snapshot_id,
arn,
encrypted
from
alicloud_ecs_snapshot
where
not encrypted;
+-------------------+------------------------+-------------------------------------------------------------------------+-----------+
| name              | snapshot_id            | arn                                                                     | encrypted |
+-------------------+------------------------+-------------------------------------------------------------------------+-----------+
| test-001-snapshot | s-a2d3rmjg71d2mnzddv58 | arn:acs:ecs:ap-south-1:5982111499156037:snapshot/s-a2d3rmjg71d2mnzddv58 | false     |
| test-002          | s-a2d3rmjg71d2mtwgq12l …
```
> Add arn column in table alicloud_ecs_snapshot. Closes #190

- alicloud/table_alicloud_vpc_eip.go
- docs/tables/alicloud_vpc_eip.md
<details>
```
```
</details>
<details>
```
select
name,
allocation_id,
arn,
description,
ip_address,
status,
region
from
alicloud_vpc_eip;
+--------+---------------------------+-------------------------------------------------------------------+-------------+---------------+-----------+------------+
| name   | allocation_id             | arn                                                               | description | ip_address    | status    | region     |
+--------+---------------------------+-------------------------------------------------------------------+-------------+---------------+-----------+------------+
| <null> | eip-a2dyiysaz6ukrjgnbo5j2 | …
```
> Add arn column in table alicloud_vpc_eip. Closes #186

- .github/workflows/golangci-lint.yml
- alicloud/canonical_policy.go
- alicloud/connection_config.go
- alicloud/monitoring_metric.go
- alicloud/multi_region.go
- alicloud/service.go
- alicloud/table_alicloud_cs_kubernetes_cluster.go
- alicloud/table_alicloud_oss_bucket.go
- alicloud/table_alicloud_ram_policy.go
- alicloud/table_alicloud_ram_user.go
- alicloud/table_alicloud_rds_instance.go
- alicloud/utils.go
<details>
```
```
</details>
<details>
```
```
</details>
> Add golangci-lint workflow #217

- alicloud/table_alicloud_rds_instance.go
<details>
```
SETUP: tests/alicloud_rds_instance []
PRETEST: tests/alicloud_rds_instance
TEST: tests/alicloud_rds_instance
Running terraform
alicloud_vpc.named_test_resource: Creating...
alicloud_vpc.named_test_resource: Creation complete after 7s [id=vpc-0xi56l3qjt6cjrb5evace]
alicloud_vswitch.named_test_resource: Creating...
alicloud_vswitch.named_test_resource: Creation complete after 7s [id=vsw-0xivzuif89u6ujqzf7hs6]
alicloud_db_instance.named_test_resource: Creating...
alicloud_db_instance.named_test_resource: Still creating... [10s elapsed]
alicloud_db_instance.named_test_resource: Still creating... [20s elapsed]
alicloud_db_instance.named_test_resource: Still creating... [30s elapsed]
alicloud_db_instance.named_test_resource: Still creating... [40s elapsed] …
```
> Update get call to handle region issue in alicloud_rds_instance table. Closes #222

- alicloud/monitoring_metric.go
<details>
```
```
</details>
<details>
```
```
</details>
> Fix Error: unexpected end of JSON input in metric statistic tables closes #224

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.1.1 closes #231

- README.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update github link for cloning the repository

- alicloud/plugin.go
- alicloud/table_alicloud_ecs_disk_metric_write_iops_hourly.go
- docs/tables/alicloud_ecs_disk_metric_write_iops_hourly.md
<details>
```
```
</details>
<details>
```
> select
instance_id,
timestamp,
minimum,
maximum,
average
from
alicloud_ecs_disk_metric_write_iops_hourly
order by
instance_id,
timestamp limit 3;
+------------------------+---------------------------+---------+---------+---------+
| instance_id            | timestamp                 | minimum | maximum | average |
+------------------------+---------------------------+---------+---------+---------+
| i-0xi3k6kddtzjqee3sjsx | 2022-03-30T18:30:00+05:30 | 0.216   | 18.966  | 1.614   |
| i-0xi3k6kddtzjqee3sjsx | 2022-03-30T19:30:00+05:30 | 0.233   | 3.533   | 0.563   |
| i-0xi3k6kddtzjqee3sjsx | 2022-03-30T20:30:00+05:30 | 0.2     | 1.283   | 0.494   | …
```
> Added table alicloud_ecs_disk_metric_write_iops_hourly. Closes #251

- alicloud/table_alicloud_ecs_disk.go
- docs/tables/alicloud_ecs_disk.md
<details>
```
```
</details>
<details>
```
> select title, attachments from alicloud_ecs_disk
+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| title                  | attachments                                                                                                                                                                                                     |
+------------------------+-------------------------------------------------------------------------------------------------------------------- …
```
> Added column attachments to table alicloud_ecs_disk. Closes #255

- alicloud/table_alicloud_vpc.go
<details>
```
```
</details>
<details>
```
> select name, arn, akas from alicloud_vpc
+------------------+--------------------------------------------------------------------+------------------------------------------------------------------------+
| name             | arn                                                                | akas                                                                   |
+------------------+--------------------------------------------------------------------+------------------------------------------------------------------------+
|                  | acs:vpc:ap-south-1:5982111499156037:vpc/vpc-a2dpygf1v0wz6x4ho9wzc  | …
```
> Add column arn to alicloud_vpc table closes #265

- alicloud/table_alicloud_ram_group.go
<details>
```
```
</details>
<details>
```
> select name, arn, akas from alicloud_ram_group
+-------------+---------------------------------------------+-------------------------------------------------+
| name        | arn                                         | akas                                            |
+-------------+---------------------------------------------+-------------------------------------------------+
| accounting  | acs:ram::5982111499156037:group/accounting  | ["acs:ram::5982111499156037:group/accounting"]  |
| cistest     | acs:ram::5982111499156037:group/cistest     | ["acs:ram::5982111499156037:group/cistest"]     |
| admingrp    | acs:ram::5982111499156037:group/admingrp …
```
> Add column arn to alicloud_ram_group table closes #264

- alicloud/table_alicloud_ram_user.go
<details>
```
```
</details>
<details>
```
> select name, arn from alicloud_ram_user;
+--------------+---------------------------------------------+
| name         | arn                                         |
+--------------+---------------------------------------------+
| testuser     | acs:ram::5982111499156037:user/testuser     |
| nw-steampipe | acs:ram::5982111499156037:user/nw-steampipe |
| abhinash     | acs:ram::5982111499156037:user/abhinash     |
| michael      | acs:ram::5982111499156037:user/michael      |
| partha       | acs:ram::5982111499156037:user/partha       |
```
```
> select name, arn, akas from alicloud_ram_user;
+--------------+---------------------------------------------+- …
```
> Add column arn to alicloud_ram_user table closes #263

- alicloud/table_alicloud_ram_user.go
<details>
```
```
</details>
<details>
```
> select name, virtual_mfa_devices from alicloud_ram_user
+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name         | virtual_mfa_devices                                                                                                                                                      |
+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sourav       | <null> …
```
> Add virtual_mfa_devices column to alicloud_ram_user table. closes #261

- alicloud/plugin.go
- alicloud/table_alicloud_rds_instance_metric_cpu_utilization_hourly.go
- docs/tables/alicloud_rds_instance_metric_cpu_utilization_hourly.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add table alicloud_rds_instance_metric_cpu_utilization_hourly. Closes #271

- alicloud-test/tests/alicloud_cas_certificate/variables.tf
- alicloud-test/tests/alicloud_cs_kubernetes_cluster_node/test-get-expected.json
- alicloud-test/tests/alicloud_cs_kubernetes_cluster_node/test-get-query.sql
- alicloud-test/tests/alicloud_cs_kubernetes_cluster_node/test-list-expected.json
- alicloud-test/tests/alicloud_cs_kubernetes_cluster_node/test-list-query.sql
- alicloud-test/tests/alicloud_cs_kubernetes_cluster_node/variables.tf
- alicloud-test/tests/alicloud_ram_user/test-hydrate-expected.json
<details>
```
Please find out the attachment below.
```
</details>
<details>
```
```
</details>
[alicloud-intg-test-result.txt](https://github.com/turbot/steampipe-plugin-alicloud/files/9445031/alicloud-intg-test-result.txt)
> Fixd integration test configuration

- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Recompile plugin wth steampipe-plugin-sdk v4.1.8

- alicloud/table_alicloud_ecs_instance.go
<details>
```
N/A
```
</details>
<details>
```
> select instance_id, ram_role from alicloud_ecs_instance
+------------------------+---------------------------------------------------------------------------+
| instance_id            | ram_role                                                                  |
+------------------------+---------------------------------------------------------------------------+
| i-0xi3k9fzy91ypr3nyslz | [{"InstanceId":"i-0xi3k9fzy91ypr3nyslz","RamRoleName":"ecsInstanceRole"}] |
+------------------------+---------------------------------------------------------------------------+
```
</details>
> Add column ram_role to table alicloud_ecs_instance closes #302

- alicloud/table_alicloud_rds_instance.go
- docs/tables/alicloud_rds_instance.md
<details>
```
> select
i.db_instance_id,
s ->> 'NetworkType' as network_type,
s ->> 'RegionId' as security_group_region_id,
s ->> 'SecurityGroupId' as security_group_id
from
alicloud_rds_instance as i,
jsonb_array_elements(security_group_configuration) as s;
+----------------------+--------------+--------------------------+-------------------------+
| db_instance_id       | network_type | security_group_region_id | security_group_id       |
+----------------------+--------------+--------------------------+-------------------------+
| rm-6gj7gsq51x7ry5mb6 | VPC          | ap-south-1               | sg-a2dhps4gidrj65iu6oya |
+----------------------+--------------+--------------------------+-------------------------+
```
</details>
> Add column `security_group_configuration` to table `alicloud_rds_instance`

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.13.1

- docs/index.md
Add explicit aggregator doc support for Alicloud plugin, same as other cloud provider
> 📝 update doc to add aggregator support

- docs/index.md
<details>
```
```
</details>
<details>
```
```
</details>
> Tidy docs/index.md file

- alicloud-test/tint.js
<details>
```
```
</details>
<details>
```
```
</details>
> Fixed the integration test script as per the latest Steampipe CLI result

- alicloud/multi_region.go
<details>
```
```
</details>
<details>
```
```
</details>
> Fix missing ap-northeast-2 in alicloudRegions

- alicloud/plugin.go
- alicloud/service.go
- alicloud/table_alicloud_alidns_domain.go
- alicloud/utils.go
- docs/tables/alicloud_alidns_domain.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add table alicloud_alidns_domain Closes #450

- alicloud/multi_region.go
<details>
```
```
</details>
<details>
```
```
</details>
> Add support for the new alicloud supported regions closes #486

- alicloud/service.go
<details>
```
```
</details>
<details>
```
> select name from alicloud_oss_bucket;
+------+
| name |
+------+
| oss1 |
+------+
```
</details>
> Enable OSS ProxyFromEnvironment by default
